---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: exampleSite/content/_index.md
  label: Home
- type: document
  path: exampleSite/content/industry.md
  label: Industry We Serve
- type: document
  path: exampleSite/content/who-we-serve.md
  label: Who We Serve
- type: document
  path: exampleSite/content/search-ads-library.md
  label: Search Ads Library
- type: directory
  path: exampleSite/content/about-us
  label: About Us
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/career
  label: Career
  create: none
  match: "**/*"
- type: directory
  path: exampleSite/content/services
  label: Services
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/contact-us
  label: Contact Us
  create: none
  match: "*"
- type: document
  path: exampleSite/content/thank-you.md
  label: Thank You
- type: document
  path: exampleSite/content/terms.md
  label: Terms
- type: document
  path: exampleSite/content/privacy.md
  label: Privacy
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Data
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
