baseURL = "https://boonze.com/"
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "boonze"
title = "SEM Company, PPC Agency, and SEO Outsourcing Services in Chennai, India"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
URL = "who-we-serve"
name = "Who We Serve"
weight = 1
[[menu.footer]]
URL = "http://www.boonze.blogspot.com/"
name = "Latest Blogs"
weight = 2
[[menu.footer]]
URL = "careers"
name = "Careers"
weight = 3
[[menu.footer]]
URL = "terms"
name = "Terms & Conditions"
weight = 10
[[menu.footer]]
URL = "privacy"
name = "Privacy Policy"
weight = 11
[[menu.main]]
URL = "industry"
name = "Industries We Serve"
weight = 2
[[menu.main]]
URL = "services"
name = "Services"
weight = 3
[[menu.main]]
URL = "search-ads-library"
name = "Search Ads Library"
weight = 4
[[menu.main]]
URL = "about-us"
name = "About Boonze"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "https://formspree.io/f/mknkrrla"
description = "This is meta description"
email = "sales@boonze.com"
home = "Home"
logo = "images/logo.webp"
mobile = "+91 9500123131"
search = false
[params.address]
address_locality = "A4, Palani Towers."
address_region = "Chennai 600017, Tamil Nadu, India"
company_name = "Boonze Media Solutions P Ltd."
street_address = "No.31, Venkatnarayana Road, T.Nagar"
[params.navigation_button]
enable = true
label = "get a quote"
link = "contact-us"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.clients_logo]]
logo = "images/clients-logo/Amazon spn.webp"
[[params.clients_logo]]
logo = "images/clients-logo/Bing ads.webp"
[[params.clients_logo]]
logo = "images/clients-logo/Facebook ads.webp"
[[params.clients_logo]]
logo = "images/clients-logo/Google ads.webp"
[[params.clients_logo]]
logo = "images/clients-logo/Instagram.webp"
[[params.clients_logo]]
logo = "images/clients-logo/LinkedIn Ads.webp"
[[params.clients_logo]]
logo = "images/clients-logo/Shopify.webp"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/boonze-media-solutions"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/SEMandPPC/"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/"
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/"
[[params.social]]
icon = "ti-twitter"
link = "https://twitter.com/boonze_media"
